### ISSUE TITLE
Python 3.9 wheels

### ISSUE THREAD

**Issue by bstellato** [cvxopt/cvxopt-wheels#7]
Would it be possible to have manylinux wheels for Python 3.9? 

I am using CVXOPT as a [test dependency for OSQP](https://github.com/oxfordcontrol/osqp-python/pull/51) but it is not straightforward to install it on CI without wheels.

Thanks a lot!

**Comment by martinandersen** [comment]
Python 3.9 wheels for macOS and manylinux are now available on PyPI.

**Comment by bstellato** [comment]
Thanks a lot for fixing it so quickly.
